In [4]:
from pathlib import Path
import geopandas as gpd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_DIR = PROJECT_ROOT / "data"
BOUNDARIES_DIR = DATA_DIR / "boundaries"

BOUNDARIES_DIR

WindowsPath('c:/Users/arjav/DevSource/toc-performance-dashboard/data/boundaries')

In [ ]:
raw_village_path = BOUNDARIES_DIR / "villages" / "Villages.shp"

village_clean_path = BOUNDARIES_DIR / "processed" / "village_clean.gpkg"

raw_village_path, village_clean_path

(WindowsPath('c:/Users/arjav/DevSource/toc-performance-dashboard/data/boundaries/villages/Villages.shp'),
 WindowsPath('c:/Users/arjav/DevSource/toc-performance-dashboard/data/boundaries/processed/village_clean.gpkg'))

In [6]:
village = gpd.read_file(raw_village_path)

print("Village features:", len(village), "| CRS:", village.crs)

village.head()

Village features: 15 | CRS: EPSG:2868

,OBJECTID,NAME,ACRES,URL,INSERT_DAT,UPDATE_DAT,ANID,geometry
0,16,Ahwatukee Foothills,22832.88,https://phoenix.gov/villages/Ahwatukee-Foothills,2022-05-05,2022-05-05,2445,"POLYGON ((683945.25 859952.062, 683930.25 8598..."
1,17,Laveen,19579.69,https://phoenix.gov/villages/Laveen,2022-05-05,2022-05-05,2444,"POLYGON ((638589.25 843376, 629247.625 838551...."
2,18,South Mountain,25481.86,https://phoenix.gov/villages/South-Mountain,2022-05-05,2022-05-05,2443,"POLYGON ((683945.25 859952.062, 683530.875 860..."
3,19,Estrella,26503.62,https://phoenix.gov/villages/Estrella,2022-05-05,2022-05-05,2442,"POLYGON ((607040.694 890232.667, 607046.417 89..."
4,20,Central City,13600.59,https://phoenix.gov/villages/Central-City,2022-05-05,2022-05-05,2441,"POLYGON ((669683.439 897001.625, 672160.625 89..."

In [7]:
PROJECT_CRS = "EPSG:2868"

def ensure_project_crs(gdf, name="layer"):
    if gdf.crs is None:
        print(f"{name}: CRS is None – set manually before reprojecting.")
        gdf = gdf.set_crs("EPSG:2868")
        return gdf
    
    if PROJECT_CRS is not None and gdf.crs != PROJECT_CRS:
        print(f"{name}: Reprojecting from {gdf.crs} to {PROJECT_CRS}")
        return gdf.to_crs(PROJECT_CRS)
    else:
        print(f"{name}: No reprojection performed.")
        return gdf

village = ensure_project_crs(village, "Village")

Village: No reprojection performed.

In [8]:
village.columns

Index(['OBJECTID', 'NAME', 'ACRES', 'URL', 'INSERT_DAT', 'UPDATE_DAT', 'ANID',
       'geometry'],
      dtype='object')

In [ ]:
VILLAGE_ID_FIELD = "OBJECTID"
VILLAGE_NAME_FIELD = "NAME"

village_clean = village[[VILLAGE_ID_FIELD, VILLAGE_NAME_FIELD, "geometry"]].copy()

village_clean.head()

,OBJECTID,NAME,geometry
0,16,Ahwatukee Foothills,"POLYGON ((683945.25 859952.062, 683930.25 8598..."
1,17,Laveen,"POLYGON ((638589.25 843376, 629247.625 838551...."
2,18,South Mountain,"POLYGON ((683945.25 859952.062, 683530.875 860..."
3,19,Estrella,"POLYGON ((607040.694 890232.667, 607046.417 89..."
4,20,Central City,"POLYGON ((669683.439 897001.625, 672160.625 89..."

In [ ]:
village_clean.to_file(village_clean_path, driver="GPKG")

print("Saved cleaned file:", village_clean_path)

Saved cleaned Village: c:\Users\arjav\DevSource\toc-performance-dashboard\data\boundaries\processed\village_clean.gpkg